### ISSUE TITLE
Post File Format & Better Permalinks

### ISSUE THREAD

**Issue by nickl1** [Fizzadar/Luapress#1]
Hello,

I would really like to see a Dropplets (https://github.com/circa75/dropplets) like post file format. Now if you edit a post it will go on the top but if you have a format like this...

```
# Post Title
- Date (e.g. "2013/04/28")
- Status (e.g. "published" or "draft")

post content
```

... it would make it more versatile.

also you could make folders inside the "posts" subfolder when compiling which will contain an index.html file to get better looking permalinks like: "/posts/this_is_my_post/".

**Comment by Fizzadar** [comment]
Couldn't agree more on the date time stuff. Will add them in the same format as mdoc ($key=value anywhere in the markdown), this will mean an optional date value (default to file modification time). Will also mean any key/value combo can be used in templates ie. author names etc.

As for drafts, I've created an empty 'drafts' folder in the /posts directory, which is where I keep my drafts, as they won't be picked up or used when generating the blog. Easier than manually doing the status in-file.

And I definitely agree on the permalinks, will see what I can do there.

Working on Luapress today, so expect to see some, if not all, of the above committed later!

**Comment by Fizzadar** [comment]
& added :)

**Comment by nickl1** [comment]
Great! You forgot to put the new theme's image files to the corresponding folder and you mistyped `date` for `data` in `README.md`. Did you make the permalinks appear without the `.html` like a folder? To me they still compile as `.html` files. I don't know if you like it like this but I'd like to at least see an option in the config file for this. ;)

Also I've got some more improvement/enchantment ideas. I'll probably post them later on a new issue ticket. You're doing a great job with Luapress. I wish I could help but I don't have the time/patience to learn lua.

edit: also the `powered by luapress →` link in the left sidebar gives me a 404 error as this page doesn't exist on my pages.
