### ISSUE TITLE
What is the <url> parameter meant to be?

### ISSUE THREAD

**Issue by kozross** [Fizzadar/Luapress#18]
Maybe I'm just stupid, but I don't understand what this should be.

**Comment by Fizzadar** [comment]
Hi @kozross - the url is to define the "base URL" of your blog/website - all the links will use this. Eg for my blog I use "http://pointlessramblings.com" as the url. A blank url would mean everything is linked from "/".

I'm leaving this issue open so I can document the URL stuff in the README.
