### ISSUE TITLE
Generating a custom index.html with posts

### ISSUE THREAD

**Issue by kozross** [Fizzadar/Luapress#19]
Is this actually possible? If I create a page called `index.md`, it does output an `index.html` page, but in `pages`, rather than at the root of the directory structure of the site.

**Comment by Fizzadar** [comment]
If there are no posts and `config.index` is an existing page name it'll use that as the index. There's currently no way to use a custom index with posts - but it's a neat feature I'd like to add.

**Comment by Fizzadar** [comment]
I have now added a `config.force_index_page` variable (and renamed `config.index` -> `config.index_page`). I'm hoping to release it/v3 over the next week. https://github.com/Fizzadar/Luapress/commit/e8c203c71a856e869745da3280b4cddbfe9023a7
