### ISSUE TITLE
error when insert image

### ISSUE THREAD

**Issue by isularifin** [Fizzadar/Luapress#33]
hi all,

i tried to insert image in markdown but i got error like this..
/usr/bin/lua: /usr/local/share/lua/5.1/luapress/lib/markdown.lua:893: attempt to call global 'encode_alt' (a nil value)
stack traceback:
    /usr/local/share/lua/5.1/luapress/lib/markdown.lua:893: in function </usr/local/share/lua/5.1/luapress/lib/markdown.lua:892>
    [C]: in function 'gsub'
    /usr/local/share/lua/5.1/luapress/lib/markdown.lua:906: in function 'images'
    /usr/local/share/lua/5.1/luapress/lib/markdown.lua:1041: in function 'span_transform'
    /usr/local/share/lua/5.1/luapress/lib/markdown.lua:724: in function 'blocks_to_html'
    /usr/local/share/lua/5.1/luapress/lib/markdown.lua:746: in function 'block_transform'
    /usr/local/share/lua/5.1/luapress/lib/markdown.lua:1108: in function 'markdown'
    /usr/local/share/lua/5.1/luapress/util.lua:181: in function '_process_content'
    /usr/local/share/lua/5.1/luapress/util.lua:227: in function 'load_markdowns'
    /usr/local/share/lua/5.1/luapress.lua:198: in function 'build'
    ...local/lib/luarocks/rocks/luapress/3.3-0/bin/luapress:195: in function 'build'
    ...local/lib/luarocks/rocks/luapress/3.3-0/bin/luapress:229: in main chunk
    [C]: ?

would you like to help me to solve the problem. Thanks alot before

**Comment by Fizzadar** [comment]
@isularifin sorry about the delay - this is now fixed @ https://github.com/Fizzadar/Luapress/releases/tag/v3.3.1
