### ISSUE TITLE
On title change: no caching

### ISSUE THREAD

**Issue by hollunder** [Fizzadar/Luapress#39]
Obviously the title should change everywhere, so everything would need to be rebuilt.
At the moment it seems only the landing, archive and RSS pages are rebuilt.
This was tested with Version 3.3.1.

**Comment by hollunder** [comment]
I just found the `--no-cache` option, which seems to work fine.
Maybe luapress can run with this option if the title changes, but only if it is no trouble.
Otherwise, sorry for bothering you with this little thing.

**Comment by Fizzadar** [comment]
@hollunder thanks for making this issue! I'll modify things to `--no-cache` when the title changes between builds.

**Comment by hollunder** [comment]
I just wondered about other parts that are likely affected in the same way, say description, tags, really anything in the header, footer and probably other files.
Maybe run with `--no-cache` if anything in the template folder changes?

There might be false positives though, template changes that would not affect everything or are too minor to be generally noticeable or no changes at all (re-saved files). For me this would be no problem so far, since Luapress finishes in an instance, but I do not know about blogs with a huge number of articles.

Have you done any performance measurements?

**Comment by Fizzadar** [comment]
I've now [remove caching entirely](https://github.com/Fizzadar/Luapress/commit/e7f519fe2ae3529a2df84b30ff50ec72e363ef4e) as it was only causing issues and the change to discount-markdown makes things super fast anyway.
