### ISSUE TITLE
Improved markdown support

### ISSUE THREAD

**Issue by hollunder** [Fizzadar/Luapress#40]
I was looking for adding a table, something that is nasty in any markup language but horrible in html.
Tables are not supported in standard markdown but there are several extensions.
Markdown.lua does not support any of them.

I sadly did not find any pure Lua implementation of markdown that supports tables. I did find [lunamark](https://github.com/jgm/lunamark), which supports some extensions and is actively developed (it appears that markdown.lua only gets ported to newer versions of Lua).
Lunamark claims to be three orders of magnitude faster the markdown.lua, which I did not verify.

I guess it could be an improvement, even though I still need to do my little table in html...

**Comment by Fizzadar** [comment]
@hollunder as of https://github.com/Fizzadar/Luapress/commit/39756f2b85d7382c792b7c4e5d1bfd8b2f9479d9, this is now possible! I'm hoping to release this as `v3.5` by the end of the year :)

**Comment by hollunder** [comment]
Thanks :)
Sorry for the late reply. I'm glad you are working more on this than I am on my blogging :)
