### ISSUE TITLE
Support `.markdown` files

### ISSUE THREAD

**Issue by paragasu** [Fizzadar/Luapress#41]
I am running Debian, so i install luapress like this

```
#luarocks install luapress
$luapress init http://myblog.com
//add someblogpost.markdown in the ./posts folder
$luapress 
```

It outputs 

```
### Luapress v3.3.1

ENV     nil
[1] Loading templates
[2] Loading posts
[3] Loading pages
[4] Building new posts
[5] Building new pages
[6] Building index pages
[8] Copying inc files

--> Press complete! Upload ./build to your website
```

But when i inspect ./build directory, it is empty. 
Did i miss any step?

**Comment by Fizzadar** [comment]
Hi @paragasu I believe this is because of the `.markdown` filename - Luapress only looks for `.md` file extensions currently.

**Comment by paragasu** [comment]
@Fizzadar yes, it works now. I am migrating from jekyll, so all my markdown is end with .markdown instead of .md

**Comment by Fizzadar** [comment]
@paragasu I still want to support files with the `.markdown` extension, so I'm going to reopen this :)
