### ISSUE TITLE
why the index file in ~/luapress/build/ is index.xml,not index.html?

### ISSUE THREAD

**Issue by luckypoem** [Fizzadar/Luapress#5]
hi.
as3:~/luapress# ./press.lua http://lp.brite.biz.st
# 
# Luapress v1.1.0 for: http://lp.brite.biz.st
# Using cache: true
# 

[1] Loading templates
        archive
        page
        footer
        header
        post
[2] Loading new posts
[3] Loading new pages
[4] Building new posts
[5] Building new pages
[6] Building index pages
[7] Building RSS
[8] Copying inc files
# 

Luapress Complete! Upload ./build to your website
# 

as3:~/luapress# ls build
inc  index.xml  pages  posts
as3:~/luapress# cd build
as3:~/luapress/build# ls
inc  index.xml  pages  posts
as3:~/luapress/build#

why the index file in ~/luapress/build/ is index.xml,not index.html?it's very strange.
tks a lot!

**Comment by Fizzadar** [comment]
Hi @luckypoem - this is intentional, you need at least one post before `index.html` will appear. `index.xml` should now be appearing at all either, which I just pushed a fix for (https://github.com/Fizzadar/Luapress/commit/d6be3347905cbf015acd2752a3f672538feccc33).

**Comment by luckypoem** [comment]
hi.
i modified press.lua as per https://github.com/Fizzadar/Luapress/commit/d6be3347905cbf015acd2752a3f672538feccc33 , but still met error.how to fix it?
as3:~/luapress# ./press.lua http://lp.brite.biz.st
#

# Luapress v1.1.0 for: http://lp.brite.biz.st

# Using cache: true

#
[1] Loading templates
        archive
        page
        footer
        header
        post
[2] Loading new posts
[3] Loading new pages
lua: ./press.lua:293: Cant make build/posts
stack traceback:
        [C]: in function 'error'
        ./press.lua:293: in main chunk
        [C]: ?
as3:~/luapress#

tks

**Comment by Fizzadar** [comment]
@luckypoem apologies for the delay - this appears to be a permissions error, does the user have write permission to `build/`?

**Comment by luckypoem** [comment]
hi.
root@as3:~/luapress# chmod -R 777 ~/luapress/
root@as3:~/luapress# ./press.lua http://lp.brite.biz.st
#

# Luapress v1.1.0 for: http://lp.brite.biz.st

# Using cache: true

#
[1] Loading templates
        archive
        page
        footer
        header
        post
[2] Loading new posts
[3] Loading new pages
lua: ./press.lua:293: Cant make build/posts
stack traceback:
        [C]: in function 'error'
        ./press.lua:293: in main chunk
        [C]: ?
root@as3:~/luapress# chown -R www-data.www-data ~/luapress/
root@as3:~/luapress# ./press.lua http://lp.brite.biz.st
#

# Luapress v1.1.0 for: http://lp.brite.biz.st

# Using cache: true

#
[1] Loading templates
        archive
        page
        footer
        header
        post
[2] Loading new posts
[3] Loading new pages
lua: ./press.lua:293: Cant make build/posts
stack traceback:
        [C]: in function 'error'
        ./press.lua:293: in main chunk
        [C]: ?
root@as3:~/luapress# chown -R root ~/luapress/
root@as3:~/luapress# ./press.lua http://lp.brite.biz.st
#

# Luapress v1.1.0 for: http://lp.brite.biz.st

# Using cache: true

#
[1] Loading templates
        archive
        page
        footer
        header
        post
[2] Loading new posts
[3] Loading new pages
lua: ./press.lua:293: Cant make build/posts
stack traceback:
        [C]: in function 'error'
        ./press.lua:293: in main chunk
        [C]: ?
root@as3:~/luapress# chown -R root.root ~/luapress/
root@as3:~/luapress# ./press.lua http://lp.brite.biz.st
#

# Luapress v1.1.0 for: http://lp.brite.biz.st

# Using cache: true

#
[1] Loading templates
        archive
        page
        footer
        header
        post
[2] Loading new posts
[3] Loading new pages
lua: ./press.lua:293: Cant make build/posts
stack traceback:
        [C]: in function 'error'
        ./press.lua:293: in main chunk
        [C]: ?
root@as3:~/luapress#

still doesn't work.how to fix it?
tks a lot for ur reply!

**Comment by luckypoem** [comment]
hi.
i recloned ur repo,this time i installed it successfully: http://lp.brite.biz.st/ ,but very strangely,the homepage only show one post,why?actually i created 4 posts:
root@as3:~/luapress-site# ls posts
black_dot_on_white_paper.md  jingle-bell.md  super-talk.md  test1.md  test2.md
root@as3:~/luapress-site# 

the archive page: http://lp.brite.biz.st/pages/Archive/ also shows only one post.the other 4 posts don't show on the site at all,why?though the other 4 posts do exist: http://lp.brite.biz.st/posts/test1/ ,
http://lp.brite.biz.st/posts/test2 , http://lp.brite.biz.st/posts/jinglebell/ , http://lp.brite.biz.st/posts/supertalk/

tks!

**Comment by Fizzadar** [comment]
Hi @luckypoem - sorry for not being in touch I only just saw this reply :( As for your error, I'm not 100% on that - could you paste a copy of your `config.lua` file here?

**Comment by luckypoem** [comment]
hi.
root@as3:~# cd ~/luapress-site
root@as3:~/luapress-site# ls
build               config.lua  lib         pages  press.lua  templates
config.example.lua  inc         LICENSE.md  posts  README.md
root@as3:~/luapress-site# cat config.lua
local config = {
    --website url
    url = 'http://lp.brite.biz.st',
    --website title
    title = 'A Lone Ship',
    --template
    template = 'default',
    --posts per page
    posts_per_page = 5,
    --link directories not files
    link_dirs = true
}

return config
root@as3:~/luapress-site#

tks a lot
