### ISSUE TITLE
Add triple backticks support for code formating & syntax highlighting

### ISSUE THREAD

**Issue by paragasu** [Fizzadar/Luapress#51]
It really nice if there is a support for triple backticks just like the one supported by jekyll and github comments.
Or should this be implemented as plugins?

**Comment by msva** [comment]
I think that even if it is possible to implement that as plugin (although, as far as I looked in the code I'm in doubt a bit about it), it will anyway be nice to have that here, in upstream.

And, by the way, it will be nice to not only support triple backtick itself (converting it to `<pre><code></code></pre>`), but also transforming <code>```langname</code> into <code>&lt;pre&gt;&lt;code lang="langname"&gt;&lt;/code&gt;&lt;/pre&gt;</code>

**Comment by paragasu** [comment]
i like your suggestion @msva .

**Comment by Fizzadar** [comment]
Tripple backticks are now supported as of https://github.com/Fizzadar/Luapress/commit/39756f2b85d7382c792b7c4e5d1bfd8b2f9479d9! I'm hoping to release this as `v3.5` by the end of the year!

As for syntax highlighting - I think that's something that should be handled outside of Luapress by using a JS library (eg [highlightjs](https://highlightjs.org/)).
