### ISSUE TITLE
plugin support for config.index_page

### ISSUE THREAD

**Issue by lhauck** [Fizzadar/Luapress#59]
I would like to see plugin support for the page specified in config.index_page - that way we can pseudo-dynamically create content on the home page.

PS: keep up the good work.  I'm really liking this.  Much simpler than Jekyll.

**Comment by Fizzadar** [comment]
@lhauck this is already possible as it turns out - the [gallery test](https://github.com/Fizzadar/Luapress/tree/develop/tests/gallery) includes a plugin rendered on the index page.
