### ISSUE TITLE
Add --watch

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/Luapress#6]

**Comment by kozross** [comment]
Is there an easy way to get this to preview? I wouldn't mind more Lua, but I currently don't have an easy way to do this.

**Comment by Fizzadar** [comment]
@kozross I'm struggling on this one - I need to find a library for handling filesystem changes/notifications, but have yet to do so.

**Comment by Fizzadar** [comment]
Since there's no suitable library - I'll roll a basic implementation using `LuaFileSystem`.

**Comment by Fizzadar** [comment]
Basic implementation @ https://github.com/Fizzadar/Luapress/commit/ab6acedb6a5ef7fff240fce3b1ea14843ba114a4
