### ISSUE TITLE
Any chance to get etlua templating support?

### ISSUE THREAD

**Issue by ryanford** [Fizzadar/Luapress#60]

**Comment by Fizzadar** [comment]
Hi @ryanford-frontend! Unfortunately I just don't have time to work on Luapress at the moment, but welcome any PRs :)!

**Comment by JordanMajd** [comment]
I have a working prototype of this, I am doing more testing then will open up a PR.

**Comment by JordanMajd** [comment]
PR #72 opened to add this feature.
