### ISSUE TITLE
fenced code block does not translate properly

### ISSUE THREAD

**Issue by 4mig4** [Fizzadar/Luapress#63]
1. Install postfix from the ``/usr/ports/mail/postfix/`` FreeBSD port or use the `pkg install postfix` command.
 1. You need to modify the Postfix file ``/usr/local/etc/posftix/main.cf`` as follows:
 \```
   myhostname = machine.localdomain.local
   myorigin = $mydomain
   inet_interfaces = $myhostname, localhost
   mydestination = $myhostname, localhost.$mydomain, $mydomain
   local_recipient_maps = unix:passwd.byname $alias_maps
   mynetworks= $config_directory/mynetworks
   relay_domains = $config_directory/relay_domains
   transport_maps = hash:$config_directory/transport
   alias_maps = hash:$config_directory/aliases
   alias_database = hash:/etc/aliases
\```

` ***** **NOTE** : This is just needed to setup our Postfix environment but you may already have done this when you installed Postfix for other usage.`
 
` 1. In Postfix ``/usr/local/etc/posftix/main.cf`` you need to modify to add:
`

Should be shown like that this (look at the source above ) : 

![blockquote_ok](https://user-images.githubusercontent.com/3671074/56341524-505f9f00-61f0-11e9-8e30-ee2b1eef4731.png)

but it show like this in luapress:

![blockquote_luapress](https://user-images.githubusercontent.com/3671074/56341578-75eca880-61f0-11e9-817b-f315e4d059f3.png)

**Comment by Fizzadar** [comment]
@4mig4 `v3.5` should fix this as it includes full support for fenced code blocks using `lua-discount`!
