### ISSUE TITLE
Creation of TOC

### ISSUE THREAD

**Issue by 4mig4** [Fizzadar/Luapress#66]
Could it be possible to add a keyword for TOC {{toc}} that would build automatically a table of content of the current post/page based on the headers of the post/page ?

**Comment by Fizzadar** [comment]
So this should now be possible using `lua-discount` - I added `toc` as a default option (https://github.com/Fizzadar/Luapress/commit/670440c96fbb2a77f11d6d4810f5f279ac9f8265) but it needs more work. Something like: `$toc=true` within a post to generate it.

**Comment by 4mig4** [comment]
Nice, looking forward to using it.

**Comment by 4mig4** [comment]
Did you manage to find a simple way to integrate it ?

**Comment by Fizzadar** [comment]
@4mig4 not yet I've not had the time, I doubt I'll be able to investigate this for a few weeks.

**Comment by Fizzadar** [comment]
This is now possible - can be rendered in-post with `$=toc` or in a template with `post.toc`.

**Comment by 4mig4** [comment]
Branch is not tagged in GITHUB so luarocks install fails
