### ISSUE TITLE
something `$toc=true` something does not render

### ISSUE THREAD

**Issue by 4mig4** [Fizzadar/Luapress#70]
I found a strange problem trying to render a \<code\>$toc=true\</code\> which should be created using markdown as : \`$toc=true\` , there are no characters in this expression that needs escaping , however it does not render at all.

You can reproduce the problem by creating a page or a post with the following content for example:

\`toc\` something something \`$toc=true\` something something

I think this is a parsing bug due to the parser trying to interpret $ as a variable, I think there is a need to differentiate the variables from the rest of the document or escape $.

**Comment by Fizzadar** [comment]
@4mig4 I believe the parser will drop any lines starting with `$`, into variables. If it's nested on the same line it should work so I will check that!

Just to note the `$toc` thing hasn't been implemented yet so nothing will appear there.

**Comment by 4mig4** [comment]
Yes I know that $toc is not implemented yet, I just used it as a test I could have written $toto=whatever as an exemple.

**Comment by Fizzadar** [comment]
Ah I see! Yeah so Luapress will basically remove any line `$<key>=`. Although it should only do this at the start of a line - so `<code>$=blah</code>` should work. Although using fenced blocks would not ie:

    ```
    $this=that
    ```

**Comment by 4mig4** [comment]
This does not seem right to forbid the use of $ as a first line character when using fenced blocks. 
code should detect that it has entered a fenced block and not try to use the variable then.

Also `$blah=whatever` does not work. 

Could you please try to remediate to this ? 

> Ah I see! Yeah so Luapress will basically remove any line `$<key>=`. Although it should only do this at the start of a line - so `<code>$=blah</code>` should work. Although using fenced blocks would not ie:
> 
> ```
> ```
> $this=that
> ```
> ```

**Comment by Fizzadar** [comment]
This should now be fixed - v4 only parses `$key=value` lines at the top of posts.
