### ISSUE TITLE
$=toc is rendered in INDEX PAGE of POSTS section

### ISSUE THREAD

**Issue by 4mig4** [Fizzadar/Luapress#84]
`$=toc` gets properly rendered ( prior to 4.1.1 it would not) but it now gets show in the INDEX PAGE of POSTS ( where the list of all recent POSTS is shown). It would be nice if this was not the case and if the rendering would not happen in this particular location.

**Comment by Fizzadar** [comment]
Thinking about this - the TOC should probably only ever render on full post pages otherwise the links won't work on an index page.

**Comment by 4mig4** [comment]
Yes that is correct the link won't work, I can confirm this.

**Comment by 4mig4** [comment]
I was wondering if you made any progress to get this fixed ?

**Comment by Fizzadar** [comment]
@4mig4 this should now be fixed as of https://github.com/Fizzadar/Luapress/commit/109990eb252af6dbaa89babe3860a98ac94cfe27; released as `v4.1.2` :)

**Comment by 4mig4** [comment]
many thanks Nick!.... it works :)
