### ISSUE TITLE
luapress.org no longer owned by project?

### ISSUE THREAD

**Issue by wbadart** [Fizzadar/Luapress#97]
Hey team- it appears that luapress.org now redirects to some unrelated spam site. I totally understand the choice not to renew the domain, but, in the interest of not exposing people curious about the project to spam, may I recommend removing references to luapress.org from the README and repo metadata?

Thanks for your consideration!

**Comment by Fizzadar** [comment]
Oh great spot @wbadart, thank you for raising this I have removed any references/links from the readme/repo.
